# autogenerated by txs
#include:expl3
\csmDefinematrix{matrix name}{rows}{columns}{entries}
\csmDeterminant{matrix name}
\csmIsMatrixSquare{matrix name}
\csmMatrixCopy{matrix name}
\csmMatrixGetItem{arg1}
\csmMatrixIdentity{matrix name}{dimention}
\csmMatrixLinComb{matrix name}[coef1]{matrix1}[coef2]{matrix2}
\csmMatrixMultiplication{matrix name}{matrix1}{matrix2}
\csmMatrixPower{matrix name}{base}{exp}
\csmMatrixSub{matrix name}{matrix1}{matrix2}
\csmMatrixSum{matrix name}{matrix1,matrix2,...}
\csmMatrixTrace{matrix name}
\csmTransposeMatrix{tr matrix name}{matrix}
\printmatrix{matrix name}
\printmatrix[style=...]{matrix name}
\__file_name=expl3.sty#S
\__file_seen_expl3.sty:#S
\__hook expl3#S
\__hook package/expl3/after#S
\__hook package/expl3/before#S
\__hook_next package/expl3/after#S
\__hook_next package/expl3/before#S
\csmDefinematrix code#S
\csmDeterminant code#S
\csmIsMatrixSquare code#S
\csmMatrixCopy code#S
\csmMatrixGetItem code#S
\csmMatrixIdentity code#S
\csmMatrixLinComb code#S
\csmMatrixMultiplication code#S
\csmMatrixPower code#S
\csmMatrixSub code#S
\csmMatrixSum code#S
\csmMatrixTrace code#S
\csmTransposeMatrix code#S
\g__hook_package/expl3/after_reversed_tl#S
\g__hook_package/expl3/before_reversed_tl#S
\key code > matrixStyle/style
\key code > matrixStyle/style/Bmatrix
\key code > matrixStyle/style/Vmatrix
\key code > matrixStyle/style/bmatrix
\key code > matrixStyle/style/matrix
\key code > matrixStyle/style/pmatrix
\key code > matrixStyle/style/unknown
\key code > matrixStyle/style/vmatrix
\key type > matrixStyle/style
\msg extra text > mymatrix/not-square#S
\msg text > mymatrix/not-square#S
\printmatrix code#S
\unprocessedoptions-expl3.sty#S
csnameendcsname#S
expl3.sty#S
